version: "3"
services:
  nginx:
    image: nginx
    working_dir: /
    volumes:
      - .:/app
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
    - php-fpm
    healthcheck:
      test: curl -I ${HEALTHCHECK_URL}
      interval: 30s
      timeout: 10s
      retries: 2
  php-fpm:
    build: docker/php
    volumes:
      - .:/app
    depends_on:
      - mysql
  mysql:
    image: mysql
    ports:
    - 3307:3306
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: 3306
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}